@echo off
@REM python playground.py --config ./configs/transnext_tiny.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 32 --input-size 128 --finetune @echo off
@REM python playground.py --config ./configs/transnext_tiny.py --data-set Food101 --data-path Dataset/Food101 --epochs 120  --batch-size 32 --input-size 128 --resume checkpoints/transnext_tiny/best.pth --pretrain-size 224 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM python playground.py --config ./configs/transnext_small.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 32 --input-size 128 --finetune models/small_imnet_finetuned/transnext_small_384_1k_ft_1k.pth --pretrain-size 384 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM python playground.py --config ./configs/transnext_tiny.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 32 --input-size 128 --resume checkpoints/transnext_tiny/best.pth --pretrain-size 224 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM python playground.py --config ./configs/transnext_small.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 32 --input-size 128 --finetune models/small_imnet_finetuned/transnext_small_384_1k_ft_1k.pth --pretrain-size 384 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM python playground.py --config ./configs/transnext_small.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 32 --input-size 128 --resume checkpoints/transnext_small/best.pth --pretrain-size 384 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM python playground.py --config ./configs/transnext_base.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 16 --input-size 128 --resume checkpoints/transnext_base/last.pth --pretrain-size 384 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM python playground.py --config ./configs/transnext_base.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 16 --input-size 128 --resume checkpoints/transnext_base/last.pth --pretrain-size 384 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
@REM For checking the time: 
python playground.py --config ./configs/transnext_tiny.py --data-set Food101 --data-path Dataset/Food101 --epochs 40 --batch-size 32 --input-size 128 --finetune models/tiny/transnext_tiny_224_1k.pth --pretrain-size 224 --lr 1e-4 --weight-decay 1e-4 --output_dir output/food101_finetune
